version: '3.8'

services:
  reactive-system-demo-wiremock:
    image: wiremock/wiremock:latest
    container_name: reactive-system-demo-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
  reactive-system-demo-db:
    image: postgres:15
    container_name: reactive-system-demo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reactive_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
